### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by adminnanfeng** [iYgnohZ/crack-geetest#3]
我下载了你的滑动验证程序之后，出现了滑动页面，但是滑动失败，不能进入，请教一下哪除了问题

**Comment by iYgnohZ** [comment]
这个程序主要讲的是思路，只在Mac Pro13上测试过。

**Comment by adminnanfeng** [comment]
图片的坐标和滑块的位置是按照mac来设置固定的吗

**Comment by iYgnohZ** [comment]
基本是这样的，流程大概是先截取全屏幕图像，然后通过验证码 HTML 元素找到顶点的位置，最后把验证码部分图片截取下来，通过像素点判断缺口的位置。
