### ISSUE TITLE
请教您一下geetest的问题

### ISSUE THREAD

**Issue by githubSunGuoQing** [iYgnohZ/crack-geetest#4]
您好，我看到到了你在知乎上对geetest的分析， 以及这里的源码，非常惊喜，晚上回家一定赶紧尝试，可以添加一下你的q吗？我的是786251107，孙国庆。同时，如果您方便，以后可以有偿帮我们实现一些破解。

**Comment by iYgnohZ** [comment]
我不用 QQ，有技术上的问题可以提 Issues 或者发邮件给我，这里只是提一个思路，如果是想让我帮你们破解验证码，建议你还是不要联系我的好。

**Comment by githubSunGuoQing** [comment]
嗯嗯，我知道了谢谢，我只是希望如果在借鉴你的源码的时候，如果有不清楚的地方，还望指教。

**Comment by githubSunGuoQing** [comment]
您好，我运行了您的源码，一切都正常，但是如何才能循环破解下去呢，我看到你这个函数里面，有复原的时间的。但是，这个demo只有两次尝试破解，想请教一下您，如何循环不断的尝试破解呢，我对这块不是太了解，因为我一直是做数据分析的，方便的话，可以指点一下吗？

**Comment by iYgnohZ** [comment]
如果想做循环破解，首先你需要判断上一次破解的状态（成功或者失败），失败继续调用 crack 函数。

判断破解状态的方法，通过解析页面中验证码返回的提示信息可以实现。
[image: 内嵌图片 1]

在 2017年4月2日 下午3:56，孙国庆 <notifications@github.com>写道：

**Comment by githubSunGuoQing** [comment]
好的，谢谢。我正在尝试
